### ISSUE TITLE
GOF: Factory and Multiton

### ISSUE THREAD

**Issue by gabibguedes** [desenho2019-1/docs#19]
Study Factory and Multiton GOFs and document it on github pages.

**Tasks:**
- [x] Study Factory
- [x] Study Multiton
- [x] Analyze what we can use in our project

**Acceptance Criteria:**
- [x] The document on pages explains what is each one of these GOFs
- [x] The document explains wich ones we can use in our project and why.
