### ISSUE TITLE
GOF: Abstract and Singleton

### ISSUE THREAD

**Issue by gabibguedes** [desenho2019-1/docs#20]
Study Abstract and Builder GOFs and document it on github pages.

**Tasks:**
- [ ] Study Abstract
- [ ] Study Singleton
- [ ] Analyze what we can use in our project

**Acceptance Criteria:**
- [ ] The document on pages explains what is each one of these GOFs
- [ ] The document explains wich ones we can use in our project and why.
