### ISSUE TITLE
GOF: Prototype, Objective Pool and Builder

### ISSUE THREAD

**Issue by gabibguedes** [desenho2019-1/docs#21]
Prototype, Objective Pool and Builder GOFs and document it on github pages.

**Tasks:**
- [x] Study Prototype
- [x] Study Objective Pool
- [x] Builder
- [ ] Analyze what we can use in our project

**Acceptance Criteria:**
- [x] The document on pages explains what is each one of these GOFs
- [ ] The document explains wich ones we can use in our project and why.
