### ISSUE TITLE
Static UML

### ISSUE THREAD

**Issue by gabibguedes** [desenho2019-1/docs#22]
Refactor the classes diagram and the package diagram according to our architecture.

**Tasks:**
- [ ] Remake classes diagram
- [ ] Refactor package diagram

**Acceptance Criteria:**
- [ ] All of the requested diagrams are updated
- [ ] The new diagrams follows the project architecture
