### ISSUE TITLE
Dynamic UML

### ISSUE THREAD

**Issue by gabibguedes** [desenho2019-1/docs#23]
Refactor the sequence diagrams according to our architecture. And make a new diagram about a sequence from outside the system

**Tasks:**
- [ ] Refactor sequence diagram 1
- [ ] Refactor sequence diagram 1
- [ ] Make a sequence diagram about processes outside the system

**Acceptance Criteria:**
- [ ] All of the requested diagrams are updated
- [ ] The new diagrams follows the project architecture
