### ISSUE TITLE
GOF: Adapter, Bridge, Composite

### ISSUE THREAD

**Issue by joaorobson** [desenho2019-1/docs#25]
Adapter, Bridge, Composite GOFs and document it on GitHub pages.

**Tasks:**
- [ ] Study Adapter
- [ ] Study Bridge
- [ ] Study Composite
- [ ] Analyze what we can use in our project

**Acceptance Criteria:**
- [ ] The document on pages explains what is each one of these GOFs
- [ ] The document explains which ones we can use in our project and why.
