### ISSUE TITLE
GOF: Decorator, Extension, Facade

### ISSUE THREAD

**Issue by joaorobson** [desenho2019-1/docs#26]
Decorator, Extension, Facade GOFs and document it on GitHub pages.

**Tasks:**
- [x] Study Decorator
- [x] Study Extension
- [x] Study Facade
- [ ] Analyze what we can use in our project

**Acceptance Criteria:**
- [ ] The document on pages explains what is each one of these GOFs
- [ ] The document explains which ones we can use in our project and why.
