### ISSUE TITLE
GOF: Flyweight, Front Controller, Marker

### ISSUE THREAD

**Issue by joaorobson** [desenho2019-1/docs#27]
Flyweight, Front Controller, Marker GOFs and document it on GitHub pages.

**Tasks:**
- [ ] Study Flyweight
- [x] Study Front Controller
- [ ] Study Marker
- [ ] Analyze what we can use in our project

**Acceptance Criteria:**
- [ ] The document on pages explains what is each one of these GOFs
- [ ] The document explains which ones we can use in our project and why.

**Comment by RomuloSouza** [comment]
I accepted partially because it was ok, but it isn't complete yet. I believe you can finish this job @gabibguedes @aleronupe :)
