### ISSUE TITLE
GOF: Module, Proxy, Twin

### ISSUE THREAD

**Issue by joaorobson** [desenho2019-1/docs#28]
Module, Proxy, Twin GOFs and document it on GitHub pages.

**Tasks:**
- [x] Study Module
- [x] Study Proxy
- [x] Study Twin
- [x] Analyze what we can use in our project

**Acceptance Criteria:**
- [x] The document on pages explains what is each one of these GOFs
- [x] The document explains which ones we can use in our project and why.
