### ISSUE TITLE
GRASP: Indirection, Information Expert, Protected Variations and Analysis of Pure Fabrication

### ISSUE THREAD

**Issue by joaorobson** [desenho2019-1/docs#29]
Indirection, Information Expert, Protected Variations GRASPs and document it on GitHub pages.

**Tasks:**
- [x] Study Indirection
- [x] Study Information Expert
- [ ] Study Protected Variations
- [ ] Write Pure Fabrication Analysis
- [ ] Analyze what we can use in our project

**Acceptance Criteria:**
- [ ] The document on pages explains what is each one of these GRASPs
- [ ] The document explains which ones we can use in our project and why.
